---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: post
polling_url: |
  https://api.hardcover.app/v1/graphql
  https://www.randomnumberapi.com/api/v1.0/randomnumber
polling_headers: content-type=application/json&authorization={{bearerToken}}
polling_body: '{"query":"query($want_to_read_limit: Int = 100) {\nme {\nname\nid\nusername\nbio\nbooks_count\nflair\nlibrarian_roles\nfollowed_users_count\nfollowers_count\nimage: cached_image\nwant_to_read_count: user_books_aggregate(where: { status_id: { _eq: 1 }}) {\naggregate {\ncount\n}\n}\ncurrently_reading_count: user_books_aggregate(where: { status_id: { _eq: 2 }}) {\naggregate {\ncount\n}\n}\nread_count: user_books_aggregate(where: { status_id: { _eq: 3 }}) {\naggregate {\ncount\n}\n}\ndid_not_finish_count: user_books_aggregate(where: { status_id: { _eq: 5 }}) {\naggregate {\ncount\n}\n}\ngoals {\ntitle: description\nread: progress\ngoal\n}\ncurrently_reading: user_books(where: {status_id: {_eq: 2}}, limit: 5, order_by: { last_read_date: desc_nulls_last }) {\nbook {\ntitle\nimage: cached_image\n}\nedition {\nimage: cached_image\n}\nrating\nupdated_at\n}\nrecently_read: user_books(where: {status_id: {_eq: 3}}, limit: 5, order_by: { last_read_date: desc_nulls_last }) {\nbook {\ntitle\nimage: cached_image\n}\nedition {\nimage: cached_image\n}\nrating\nupdated_at\n}\nwant_to_read: user_books(where: { status_id: { _eq: 1 } }, limit: $want_to_read_limit, order_by: {date_added: asc}) {\nbook {\nid\ntitle\nimage: cached_image\n}\nedition {\nimage: cached_image\n}\n}\n}\n}"}'
id: 63345
custom_fields:
- keyname: authorBio
  name: About This Plugin
  field_type: author_bio
  description: |
    Hardcover is a social network for book lovers to find life changing books, track what you read & want to read, and connect with passionate readers.

    This plugin displays your account statistics and goals, as well as the books you've recently read, are currently reading, or want to read.
  github_url: https://github.com/jacobtender/hardcover_trmnl
  learn_more_url: https://hardcover.app?referrer_id=8753
  email_address: hardcover@jacobtender.net
- keyname: bearerToken
  field_type: string
  name: Bearer Token
  description: Copy value from https://hardcover.app/account/api
  placeholder: Bearer xxx
- keyname: featuredArea
  field_type: select
  options:
  - Goals
  - Recently Read
  - Currently Reading
  - Shuffle Want To Read
  default: goals
  name: Featured Area
  description: Select what appears in the lower half in a full view.
name: Hardcover
refresh_interval: 360
